name: Build Hugo

on:
  push:
    branches: [ main ] # Trigger the action on push events to the main branch
  pull_request:
    branches: [ main ] # Optionally, trigger the action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        repository: chx9/chx9.github.io
        submodules: 'recursive'  # Ensures submodules are checked out

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo  # Generate the public folder with Hugo

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Automated deployment to GitHub Pages'
        repository: 'chx9/chx9.github.io'
